# Generated by Django 3.0.3 on 2020-09-29 21:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('veg', models.BooleanField(default=False)),
                ('isAddOn', models.BooleanField(default=False)),
                ('images', models.ImageField(default='items/Category/default.jpg', upload_to='items/Category')),
                ('addOnPrice', models.IntegerField(blank=True, null=True)),
                ('extras', models.ManyToManyField(blank=True, related_name='category', to='items.AddOn')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('veg', models.BooleanField(default=False)),
                ('availaible', models.BooleanField(default=True)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price4', models.DecimalField(decimal_places=2, max_digits=8)),
                ('spice', models.BooleanField(default=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/menu')),
            ],
        ),
        migrations.CreateModel(
            name='Option1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Option2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.IntegerField(unique=True)),
                ('availaible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('availaible', models.BooleanField(default=True)),
                ('spice', models.BooleanField(default=True)),
                ('veg', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/items')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='items.Category')),
                ('options', models.ManyToManyField(blank=True, related_name='Items', to='items.Option2')),
                ('suggestions', models.ManyToManyField(blank=True, related_name='related_to', to='items.Item')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='category', to='items.Option1'),
        ),
    ]
