# Generated by Django 3.0.3 on 2020-09-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='spice',
            new_name='option1',
        ),
    ]
