# Generated by Django 3.0.3 on 2020-09-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200930_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='addOnPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
