# Generated by Django 3.0.3 on 2020-10-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200930_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='unique_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
