# Generated by Django 3.0.3 on 2020-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_table_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addOn',
            field=models.BooleanField(default=False),
        ),
    ]
