# Generated by Django 3.0.3 on 2020-10-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20201019_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]
