# Generated by Django 3.0.3 on 2020-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_menu_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='addOn',
            field=models.BooleanField(default=False, verbose_name='Extras'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price2',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price for 2 person'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price3',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price for 3 person'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price4',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price for 4 person'),
        ),
    ]
