# Generated by Django 3.0.3 on 2020-10-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20201019_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='isAddOn',
        ),
    ]
