# Generated by Django 3.0.3 on 2020-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20201019_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tableNumber',
            field=models.IntegerField(unique=True, verbose_name='Table Number'),
        ),
    ]
