# Generated by Django 3.0.3 on 2020-09-29 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('addOn', models.CharField(blank=True, max_length=50, null=True)),
                ('spice', models.CharField(blank=True, max_length=25, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.Item')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='items.Menu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('orderDate', models.DateTimeField(blank=True, null=True)),
                ('starters', models.BooleanField(default=False)),
                ('orderID', models.IntegerField(blank=True, null=True)),
                ('item', models.ManyToManyField(to='order.OrderItem')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Table')),
            ],
        ),
    ]
