# Generated by Django 3.0.3 on 2020-10-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='spice',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='option2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='addOn',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
